/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ProjectsSlugPostSlugRouteImport } from './routes/projects/$slug.$postSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugPostSlugRoute = ProjectsSlugPostSlugRouteImport.update({
  id: '/$postSlug',
  path: '/$postSlug',
  getParentRoute: () => ProjectsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/$slug/$postSlug': typeof ProjectsSlugPostSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/$slug/$postSlug': typeof ProjectsSlugPostSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/$slug/$postSlug': typeof ProjectsSlugPostSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/$slug' | '/projects/$slug/$postSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$slug' | '/projects/$slug/$postSlug'
  id: '__root__' | '/' | '/projects/$slug' | '/projects/$slug/$postSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/$postSlug': {
      id: '/projects/$slug/$postSlug'
      path: '/$postSlug'
      fullPath: '/projects/$slug/$postSlug'
      preLoaderRoute: typeof ProjectsSlugPostSlugRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
  }
}

interface ProjectsSlugRouteChildren {
  ProjectsSlugPostSlugRoute: typeof ProjectsSlugPostSlugRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugPostSlugRoute: ProjectsSlugPostSlugRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
